# Generated by Django 6.0.2 on 2026-02-14 01:57

import short_urls.services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=600)),
                ('id_token', models.CharField(default=short_urls.services.create_formated_uuid, max_length=9)),
                ('short_url', models.SlugField()),
            ],
        ),
    ]
