# Generated by Django 6.0.2 on 2026-02-14 21:35

import short_urls.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturls',
            name='id_token',
            field=models.CharField(default=short_urls.services.create_formated_uuid, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='shorturls',
            name='short_url',
            field=models.CharField(max_length=50),
        ),
    ]
