# Generated by Django 6.0.2 on 2026-02-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0002_alter_shorturls_id_token_alter_shorturls_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturls',
            name='original_url',
            field=models.URLField(max_length=5000),
        ),
    ]
